# file: .air.toml

root = "."
tmp_dir = "bin"

[build]
  bin = "./bin/main"
  args_bin = ["serve"]
  cmd = "npx tailwindcss -i ./pb_public/main.css -o ./pb_public/tailwind.css && $(go env GOPATH)/bin/templ generate && go build -o ./bin/main ."
  delay = 1000
  exclude_dir = ["node_modules"]
  exclude_regex = [".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  include_ext = ["go", "tpl", "tmpl", "templ", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true
